# \u5E94\u7528\u540D\u79F0
spring:
  application:
    name: mongodb
server:
  port: 9090
  servlet:
    session:
      timeout: 60000

logging:
  level:
    root: warn
    com.king: info
    org.springframework: error
  file:
    name: ../log/mybatis-plus.log
swagger:
  enable: true
